### ISSUE TITLE
adopt gnome version-scheme?

### ISSUE THREAD

**Issue by poinck** [poinck/lampe#18]
version numbers based on gtk+-version used for lampe-gtk, starting with 3.13.1 or 3.15.1 for first pre-release.

**Comment by FSMaxB** [comment]
I don't see the point in this because lampe isn't following the GNOME 3 and GTK release cycle and all it brings is confusion.

**Comment by poinck** [comment]
I see your point.

**Comment by poinck** [comment]
Ok, version scheme will stay as it is.
