### ISSUE TITLE
Non-hue Bulbs

### ISSUE THREAD

**Issue by siam28** [poinck/lampe#22]
poinck. I'm a big fan of the bash script and use this on a headless RPi frequently.

I have some non Hue bulbs (specifically 4 GE Link bulbs and 2 Lux bulbs) connected to my bridge.
These bulbs do not have hue, saturation, or temperature settings.
I do not think the script is considering this possibility as this is what I get when I try to get the bulb states. LR1, LR2, LR3, LR4, LR5, and BR1 are Hue bulbs while all others are non Hue bulbs.

> 1  reachable  C  "LR1"
> 2  reachable  C  "LR2"
> 3  reachable  C  "LR3"
> 4  reachable  C  "LR4"
> 8  reachable  C  "BR1"
>./lampe: line 388: [: -lt: unary operator expected
>./lampe: line 391: [: -gt: unary operator expected
>./lampe: line 394: [: -gt: unary operator expected
>./lampe: line 397: [: -gt: unary operator expected
>./lampe: line 400: [: -gt: unary operator expected
>./lampe: line 403: [: -gt: unary operator expected
>./lampe: line 406: [: -gt: unary operator expected
>10  reachable  C  "HW1"`

Screenshot:
![screenshot_2015-07-26_06-43-37](https://cloud.githubusercontent.com/assets/7042576/8893526/3ac610c8-3361-11e5-9c68-30cb5bada3f4.png)

I get similar messages when I select a non-Hue bulb to try to turn them on/off or change brightness. There's another issue there (I can turn a non-Hue bulb off but not back on) but that may be addressed if the issue of non-Hue bulbs is directly addressed first.

**Comment by poinck** [comment]
Hi, thx for using it. (: And yes, you are right, I didn't implement support for lights that don't have all typical light attributes.

The script needs to make decissions based on "modelid" of the light. Could you do a GET request on your bridge, so that I can find out the modelids of your lights?

```.sh
curl "http://192.168.2.17/api/lampe-bash/lights"
```

Of course, you need to change the IP which you can get from `~/.lamperc`. It could take a while longer to fix this. I plan to fix it in version 1.1.1.2 and later it will be available in the latest development-version. Which version you are using? On Arch linux you maybe have v1.1.2 and there won't be a version lower than that, so you maybe need to wait until I have released the new preleae 1.1.3. I am currently working on (lots of commits I didn't pushed yet for the gtk+-client).

**Comment by FSMaxB** [comment]
@poinck: I can change the version policy for the AUR package if you want to. (like e.g. only using versions that you marked as stable).

**Comment by siam28** [comment]
Sure poinck. Here are the modelids, along with manufacturer and type from the curl command (from a python script):

> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: GE_Appliances, modelid; ZLL Light, type: Dimmable light
> manufacturername: GE_Appliances, modelid; ZLL Light, type: Dimmable light
> manufacturername: Philips, modelid; LCT001, type: Extended color light
> manufacturername: GE_Appliances, modelid; ZLL Light, type: Dimmable light
> manufacturername: GE_Appliances, modelid; ZLL Light, type: Dimmable light
> manufacturername: Philips, modelid; LWB004, type: Dimmable light
> manufacturername: Philips, modelid; LWB004, type: Dimmable light

I am using v1.1.2. I have no issues reverting to 1.1.1.X if needed.

**Comment by poinck** [comment]
@siam28 Thx, hopefully it will not take too long to add support for `ZLL` and `LWB004`. 

@FSMaxB I am not sure. Arch users want the latest stuff, I remember. ^^

**Comment by poinck** [comment]
@siam28 could you test this version? https://github.com/poinck/lampe/blob/v1.1.1/lampe (if that works for you I can remove debugging traces and merge to master)

**Comment by siam28** [comment]
The operand messages are gone when getting non-Hue light information and switching to non-Hue lights. Thank you very much for addressing this so quickly.

When trying to get the information for a non-Hue light (by pressing "i"), I am getting the following message (for both Lux and GE bulbs):
>  ./lampe: line 433: {"state": {"on":true: syntax error: operand expected (error token is >"{"state": {"on":true")
>./lampe: line 439: {"state": {"on":true: syntax error: operand expected (error token is > >"{"state": {"on":true")

Screenshot (light 10 is a non-hue light):
![bulb-info-error](https://cloud.githubusercontent.com/assets/7042576/8895970/01e850c2-33bb-11e5-8588-7c28af0abd0a.png)

As for turning them on/off, I'm able to turn the Lux lights on/off without issues.
But for the GE link lights, I'm only able to turn them off. I cannot turn them back on from lampe after turning them off. No error/warning messages are shown.
Curiously, when switching to a Lux light that is on, the color indicator is at a meaningful position, but when switching to a GE link light that is on, the indicator is at the left-most position. Don't know if this would be related to the issue of not being able to turn them on.

Screenshots (light 11 is a GE link light and light 17 is a Lux light):
![bulb-11](https://cloud.githubusercontent.com/assets/7042576/8895972/06bceb30-33bb-11e5-865b-062c9dff2a95.png)

![bulb-17](https://cloud.githubusercontent.com/assets/7042576/8895975/0e2ecbc2-33bb-11e5-8140-574d04509c49.png)

**Comment by poinck** [comment]
maybe too fast. /: Thx for testing, anyway. (:

It seems the GE link lights (`ZLL`) is missing more than just "saturation" and "hue". I need the complete json-output of `curl "http://192.168.2.17/api/lampe-bash/lights"` to be sure. On the other hand the error-message looks like a typo.

The meaningful setting is the default setting if some values could not be received from the bridge.

I'll let you know if there is something new to try.

**Comment by poinck** [comment]
https://github.com/poinck/lampe/blob/v1.1.1/lampe is ready for testing.

by the way, do you see `DEBUG hbSendLightsState().modelid = "ZLL"` or `DEBUG hbSendLightsState().modelid = "LWB004"` traces when switching a light on

**Comment by siam28** [comment]
The complete json-output is shown below. I've omitted the unique-ids. The state of a GE link light and Hue lights are only comprised of the fields: "on", "bri", "alert", and "reachable". I do see:
> DEBUG hbSendLightsState().modelid = "LWB004" 
> DEBUG hbSendLightsState().modelid = "ZLL Light"

when I try to turn on the Lux and GE link lights. The GE link lights do not turn on however.

JSON output:

```javascript
{
  "1": {
    "state": {
      "on": false,
      "bri": 1,
      "hue": 14910,
      "sat": 144,
      "effect": "none",
      "xy": [
        0.4596,
        0.4105
      ],
      "ct": 369,
      "alert": "select",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "LR1",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013452",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "2": {
    "state": {
      "on": false,
      "bri": 1,
      "hue": 14910,
      "sat": 144,
      "effect": "none",
      "xy": [
        0.4596,
        0.4105
      ],
      "ct": 369,
      "alert": "none",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "LR2",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013452",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "3": {
    "state": {
      "on": false,
      "bri": 1,
      "hue": 14910,
      "sat": 144,
      "effect": "none",
      "xy": [
        0.4596,
        0.4105
      ],
      "ct": 369,
      "alert": "none",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "LR3",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013452",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "4": {
    "state": {
      "on": false,
      "bri": 1,
      "hue": 14910,
      "sat": 144,
      "effect": "none",
      "xy": [
        0.4596,
        0.4105
      ],
      "ct": 369,
      "alert": "select",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "LR4",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013452",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "8": {
    "state": {
      "on": false,
      "bri": 254,
      "hue": 14910,
      "sat": 144,
      "effect": "none",
      "xy": [
        0.4596,
        0.4105
      ],
      "ct": 369,
      "alert": "select",
      "colormode": "ct",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "BR1",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013187",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "10": {
    "state": {
      "on": true,
      "bri": 254,
      "alert": "none",
      "reachable": true
    },
    "type": "Dimmable light",
    "name": "HW1",
    "modelid": "ZLL Light",
    "manufacturername": "GE_Appliances",
    "swversion": "1197632",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "11": {
    "state": {
      "on": true,
      "bri": 254,
      "alert": "none",
      "reachable": true
    },
    "type": "Dimmable light",
    "name": "HW2",
    "modelid": "ZLL Light",
    "manufacturername": "GE_Appliances",
    "swversion": "1197632",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "12": {
    "state": {
      "on": false,
      "bri": 69,
      "hue": 13091,
      "sat": 213,
      "effect": "none",
      "xy": [
        0.5134,
        0.4149
      ],
      "ct": 467,
      "alert": "none",
      "colormode": "xy",
      "reachable": true
    },
    "type": "Extended color light",
    "name": "LR5",
    "modelid": "LCT001",
    "manufacturername": "Philips",
    "swversion": "66013187",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "15": {
    "state": {
      "on": false,
      "bri": 254,
      "alert": "none",
      "reachable": false
    },
    "type": "Dimmable light",
    "name": "Entrance",
    "modelid": "ZLL Light",
    "manufacturername": "GE_Appliances",
    "swversion": "1197632",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "16": {
    "state": {
      "on": true,
      "bri": 254,
      "alert": "none",
      "reachable": false
    },
    "type": "Dimmable light",
    "name": "HW3",
    "modelid": "ZLL Light",
    "manufacturername": "GE_Appliances",
    "swversion": "1197632",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "17": {
    "state": {
      "on": true,
      "bri": 254,
      "alert": "none",
      "reachable": true
    },
    "type": "Dimmable light",
    "name": "K1",
    "modelid": "LWB004",
    "manufacturername": "Philips",
    "swversion": "66012040",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  },
  "18": {
    "state": {
      "on": true,
      "bri": 254,
      "alert": "none",
      "reachable": true
    },
    "type": "Dimmable light",
    "name": "K2",
    "modelid": "LWB004",
    "manufacturername": "Philips",
    "swversion": "66012040",
    "pointsymbol": {
      "1": "none",
      "2": "none",
      "3": "none",
      "4": "none",
      "5": "none",
      "6": "none",
      "7": "none",
      "8": "none"
    }
  }
}
```

**Comment by poinck** [comment]
I see, this is because the modelid is `"ZLL Light"` not `"ZLL"`. I can solve this, one moment please.

**Comment by poinck** [comment]
https://github.com/poinck/lampe/blob/v1.1.1/lampe is ready for the next test.

**Comment by siam28** [comment]
The off/on issue with the GE link lights are resolved. I can successfully turn all the lights on/off. Thank you poinck!

The only issue that remains is when I try to get the information of a non-Hue bulb by pressing i (lowecase), I get this error message:

```
./lampe: line 443: {"state": {"on":false: syntax error: operand expected (error token is "{"state": {"on":false")
```

**Comment by poinck** [comment]
(:

The rest I will fix over the weekend, remove the debugging traces and merge it to master. Thx for being so patient with testing.

**Comment by poinck** [comment]
https://github.com/poinck/lampe/blob/v1.1.1/lampe is ready for the final test.

**Comment by siam28** [comment]
Everything is working great. No error messages when retrieving information for a non-Hue bulb. Thanks again poinck.
