### ISSUE TITLE
urxvt Issue

### ISSUE THREAD

**Issue by siam28** [poinck/lampe#23]
Hi again poinck.

Just wanted to point out a weird display/line folding issue I'm observing when using the [urxvt terminal] (https://wiki.archlinux.org/index.php/Rxvt-unicode) application. 

In urxvt, the program starts up fine
![lampe-urxvt-startup](https://cloud.githubusercontent.com/assets/7042576/9027673/5ff4dafc-392c-11e5-8cfa-0ae3f008d28b.jpg)

But when I select a light number (1 in this case) this is what happens:
![lampe-urxvst-select](https://cloud.githubusercontent.com/assets/7042576/9027677/8b2a06e8-392c-11e5-950f-a9db0b74041c.jpg)

I've been able to reproduce the issue on my RPi and my arch linux laptop. The program looks fine on the other terminals I've tried (gnome, xfce, and st).

**Comment by poinck** [comment]
I have tested with `rxvt` without unicode-support, this works. With `urxvt` unfortunately this is reproducalbe. Currently a line is reprinted by deleting characters before the cursor one by one. `urxvt` does not stop at the first position of the line, jumps to the line above instead. So, I need a better way to clear a line.

![bildschirmfoto von 2015-08-03 21 32 58](https://cloud.githubusercontent.com/assets/1297960/9045905/5811b0ca-3a27-11e5-94c0-b392a90f5938.png)

I am not sure if this behavior can be configured in `urxvt`
