### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [poinck/lampe#28]
Hi Andre,
I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

I noticed in your hbRegisterUser method you are passing the username in your POST body.  This will start failing around February 2016,  so it will need removing/changing.   The randomly generated bridge username will be returned in the bridge response.  Apologies for the inconvenience.

Thanks
Steve

**Comment by poinck** [comment]
Hi Steve,

thx for reminding me. This will be now Prio 1.

**Comment by SteveyO** [comment]
Thanks Andre.  Great!  I will monitor it over the coming weeks!

**Comment by poinck** [comment]
working, but still needs testing with new bridge-version.

**Comment by murzz** [comment]
It works with my new bridge
