### ISSUE TITLE
lampe-gtk not showing much at all

### ISSUE THREAD

**Issue by towo** [poinck/lampe#32]
lampe on the cli displays all the lights just fine, but running the GTK version gives me no list of the lamps themselves; the bridge IP is displayed.

On the command line, missing objects occur:
(lampe-gtk:3319): Json-CRITICAL **: json_node_get_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed

(lampe-gtk:3319): Json-CRITICAL **: json_object_get_members: assertion 'object != NULL' failed

(lampe-gtk:3319): Json-CRITICAL **: json_node_get_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed

(lampe-gtk:3319): Json-CRITICAL **: json_object_get_members: assertion 'object != NULL' failed

**Comment by poinck** [comment]
It seems, I've found the problem. lampe-gtk is still using the static bridge-user "lampe-bash", but it needs to read the user from `~/.lamperc`.

**Comment by poinck** [comment]
Can you please test the fix? (see latest commit)

**Comment by towo** [comment]
Will test soon™

**Comment by murzz** [comment]
Lights are populated now, thanks.

**Comment by towo** [comment]
That fixes it, thanks.

**Comment by poinck** [comment]
Thx for testing. I can release lampe-1.1.5 soon.
