### ISSUE TITLE
lampe-gtk: replace deprecated functions

### ISSUE THREAD

**Issue by poinck** [poinck/lampe#33]
- [ ] replace depricated functions of GTK
- [ ] fix other compiler warnings

**Comment by NerosTie** [comment]
Yep, it's an issue:

![lampe](https://cloud.githubusercontent.com/assets/4572452/14728053/a42c07f2-0831-11e6-8f62-5ca28b125ee7.png)

The interface is broken on Archlinux :open_mouth:  

I can still use it but I can't change the brightness of lights.

**Comment by poinck** [comment]
Is it broken if you switch to the default gnome-theme Adwaita? Did you compile from source or are you using the packaged version in Arch?

**Comment by poinck** [comment]
Ok, it seems, it stops working with gtk+-3.20, is it already in Arch?

**Comment by NerosTie** [comment]
> if you switch to the default gnome-theme Adwaita? 

I can't, in fact I'm on KDE. It's a theme for GTK apps to look like a Qt app. It was ok with Lampe then an update broke it.

> source or are you using the packaged version in Arch?

Packaged.

> it stops working with gtk+-3.20, is it already in Arch

Yes.

**Comment by NerosTie** [comment]
The kind of errors I have:

```
(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3757:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3758:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3759:43: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3760:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3765:19: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3768:42: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3769:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3770:45: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3771:43: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3894:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(lampe-gtk:8407): Gtk-WARNING **: Theme parsing error: gtk.css:3902:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'
```

My console is full of these errors.

**Comment by poinck** [comment]
Is it possible for you to compile from source?

**Comment by NerosTie** [comment]
Actually, the package in Arch is from source.

I've reinstalled it, but unfortunately, there is no difference.

**Comment by poinck** [comment]
It seems this is a problem of the theme you are using. I've just installed an Arch system as a VM to test and `lampe-gtk` is only missing it's colors in the UI, but it works without any runtime errors, just the expected compiler-warnings due to depricated functions:

![lampe_on_gnome320](http://dateien.poinck.de/lampe_on_gnome320.png)

Of course, I assume, replacing the deprecated function would add support for the QT-theme.

**Comment by NerosTie** [comment]
> It seems this is a problem of the theme you are using. 

It seems that there is an issue with the Breeze theme for GTK3 apps (it's ok for GTK2 apps like Chromium). I've switched back to the "default" theme (which is Adwaita I think) and the interface of Lampe is not broken anymore.  
But I don't know if this issue comes from the deprecated functions you use in Lampe or if it's a real bug in `kde-gtk-config`.

**Comment by poinck** [comment]
I think it is a combination of both.

**Comment by NerosTie** [comment]
Well, the interface is not broken anymore. I mean I can use the dark theme of Breeze for GTK apps in KDE with Lampe again. So, it was definitely not an issue with Lampe. And no more errors in the terminal :tada:

**Comment by poinck** [comment]
Cool, but I will leave this issue open, although it is not critical anymore.

**Comment by poinck** [comment]
The development of lampe-gtk will not be resumed as it is now. Maybe there will be a new project someday using libadwaita.
