### ISSUE TITLE
division by 0 on redshift set

### ISSUE THREAD

**Issue by bserem** [poinck/lampe#45]
I am starting lampe and I get:
```
    redshift_options="-1 37.98:23.73 -t 6500:2700"
```
Which I have configured in `~/.lamperc` like this:
```
bridgeip="192.168.2.2"                                                           
redshift_options="-1 37.98:23.73"                                                
redshift_options="${redshift_options} -t 6500:2700"
```

And when I press `t` I get:
```
 5 /usr/bin/lampe: line 230: 1000000 / kelvin : division by 0 (error token is "kelvin ")
```
(where 5 is the lamp id).

Something wrong with my config or something going on with lampe?

**Comment by poinck** [comment]
I will look in to it.

One thing I noticed in your redshift_options: it should be `-l ` instead `-1` for location.

**Comment by bserem** [comment]
Changing the typo to `-l` fixed the problem.
Thanks!
