### ISSUE TITLE
Redshift not working (or i'm misunderstanding)

### ISSUE THREAD

**Issue by dalexanderio** [poinck/lampe#50]
I have my location set in lights-defaults, however when I enable redshift on a light it seems to make it quite bright and blue. Really, I'm not sure how to use this feature and cant seem to find any documentation on it. Is there anything else that needs to be done other than pressing "t" on a light?

**Comment by poinck** [comment]
There maybe some bulbs arround that don't have the capability to set color temperature. Here is an example how the configuration in "~/.config/lampe/light-defaults" could look like. Changes apply only after restart of **lampe**. 

```
redshift_options="-l 52.52:13.40 -t 12000:1000"
```

Please note, that I pushed the code over to GitLab, so this version here could be out of date. You could try the latest version from branch [release1.1.11](https://gitlab.com/poinck/lampe/-/tree/release1.1.11) and see if the problem still persists. This version requires `jq` to be installed on your system. When hitting capital *I* it can show some of the bulb-capabilities.
